### ISSUE TITLE
Any more demo on the usage of UpsertStreamTableSink?

### ISSUE THREAD

**Issue by kylemeow** [fhueske/table-demo#1]
Hello,

I am currently trying to enhance Flink by completing the support of UpsertStreamTableSink & UpsertStream, but I could not find any usable examples or detailed information except for some code here. 

I know that this feature is largely incomplete, however, I would like to see if there are any more practical usages or info about UpsertStreamTableSink to make sure my understanding does not deviate from the original ideas of Flink developers.

I am not sure whether it is appropriate to submit an issue here, nevertheless I find this project useful for me : )

Thank you 😄

**Comment by fhueske** [comment]
Hi @kylemeow,

This repo contains code for a simple demo. I'm not aware of more examples for `UpsertStreamTableSink`s, except those uses in the Flink tests. But those are very simple.
The community is working on adding new connectors. Contributions are welcome in case you'd like to share your code.

Thanks, Fabian

**Comment by kylemeow** [comment]
Thank you for your reply, now I have finished the first step : )
